
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 12 15:17:23 EDT 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int TIMES = 4;
  public static final int READ = 12;
  public static final int ELSE = 18;
  public static final int PLUS = 2;
  public static final int RPAREN = 7;
  public static final int INT = 8;
  public static final int EQUAL = 23;
  public static final int SEMI = 20;
  public static final int IDENTIFIER = 25;
  public static final int END = 16;
  public static final int RETURN = 13;
  public static final int ERROR = 19;
  public static final int IF = 17;
  public static final int LPAREN = 6;
  public static final int WRITE = 11;
  public static final int QUOTE = 26;
  public static final int BEGIN = 15;
  public static final int ISEQUAL = 21;
  public static final int STRING = 10;
  public static final int COMMA = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int MAIN = 14;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int INTNUMBER = 27;
  public static final int REALNUMBER = 28;
  public static final int REAL = 9;
  public static final int ISNOTEQUAL = 22;
}

